In [1]:
#imbd data set

In [2]:
import pandas as pd
import numpy as np
import warnings 
warnings.filterwarnings('ignore')
import matplotlib.pyplot as plt

In [3]:
df= pd.read_csv('/Users/anishgulhane/Downloads/datasets after 14 sept/IMDB Dataset.csv')

In [4]:
df.shape

(50000, 2)

In [5]:
df.head()

,review,sentiment
0,One of the other reviewers has mentioned that ...,positive
1,A wonderful little production. <br /><br />The...,positive
2,I thought this was a wonderful way to spend ti...,positive
3,Basically there's a family where a little boy ...,negative
4,"Petter Mattei's ""Love in the Time of Money"" is...",positive


In [6]:
df.tail()

,review,sentiment
49995,I thought this movie did a down right good job...,positive
49996,"Bad plot, bad dialogue, bad acting, idiotic di...",negative
49997,I am a Catholic taught in parochial elementary...,negative
49998,I'm going to have to disagree with the previou...,negative
49999,No one expects the Star Trek movies to be high...,negative


In [7]:
df.isnull().sum()

review       0
sentiment    0
dtype: int64

In [8]:
df.value_counts()

review                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  

In [9]:
df = df.rename(columns = {'sentiment': 'Y','review': 'X'})

In [10]:
df.head()

,X,Y
0,One of the other reviewers has mentioned that ...,positive
1,A wonderful little production. <br /><br />The...,positive
2,I thought this was a wonderful way to spend ti...,positive
3,Basically there's a family where a little boy ...,negative
4,"Petter Mattei's ""Love in the Time of Money"" is...",positive


In [11]:
import nltk #  natural language tool kit (library used in NLP)
from nltk.corpus import stopwords

In [12]:
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to
[nltk_data]     /Users/anishgulhane/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


True

In [13]:
stopwords.words('english')

['a',
 'about',
 'above',
 'after',
 'again',
 'against',
 'ain',
 'all',
 'am',
 'an',
 'and',
 'any',
 'are',
 'aren',
 "aren't",
 'as',
 'at',
 'be',
 'because',
 'been',
 'before',
 'being',
 'below',
 'between',
 'both',
 'but',
 'by',
 'can',
 'couldn',
 "couldn't",
 'd',
 'did',
 'didn',
 "didn't",
 'do',
 'does',
 'doesn',
 "doesn't",
 'doing',
 'don',
 "don't",
 'down',
 'during',
 'each',
 'few',
 'for',
 'from',
 'further',
 'had',
 'hadn',
 "hadn't",
 'has',
 'hasn',
 "hasn't",
 'have',
 'haven',
 "haven't",
 'having',
 'he',
 "he'd",
 "he'll",
 'her',
 'here',
 'hers',
 'herself',
 "he's",
 'him',
 'himself',
 'his',
 'how',
 'i',
 "i'd",
 'if',
 "i'll",
 "i'm",
 'in',
 'into',
 'is',
 'isn',
 "isn't",
 'it',
 "it'd",
 "it'll",
 "it's",
 'its',
 'itself',
 "i've",
 'just',
 'll',
 'm',
 'ma',
 'me',
 'mightn',
 "mightn't",
 'more',
 'most',
 'mustn',
 "mustn't",
 'my',
 'myself',
 'needn',
 "needn't",
 'no',
 'nor',
 'not',
 'now',
 'o',
 'of',
 'off',
 'on',
 'once',
 'on

In [14]:
len(stopwords.words('english'))

198

In [15]:
import string 
string.punctuation

'!"#$%&\'()*+,-./:;<=>?@[\\]^_`{|}~'

In [16]:
df['X'] = df['X'].str.lower()

In [17]:
l1 = stopwords.words(('english'))
def text_process(mess):
    """
    1. remove the punctuation 
    2. remove the stopwords
    3. return the list of clean textwords
    """
    nopunc = [char for char in mess if char not in string.punctuation]
    nopunc = "".join(nopunc)

    return[ word for word in nopunc.split() if word not in l1 ]

In [18]:
from sklearn.feature_extraction.text import CountVectorizer
# assign a ID/token number to each word

In [19]:
bow_transformer = CountVectorizer(analyzer=text_process).fit(df["X"])

In [20]:
len(bow_transformer.vocabulary_)

181543

In [21]:
tdm = bow_transformer.transform(df['X'])

In [22]:
tdm.shape

(50000, 181543)

In [23]:
type(tdm)

scipy.sparse._csr.csr_matrix

In [24]:
df.head()

,X,Y
0,one of the other reviewers has mentioned that ...,positive
1,a wonderful little production. <br /><br />the...,positive
2,i thought this was a wonderful way to spend ti...,positive
3,basically there's a family where a little boy ...,negative
4,"petter mattei's ""love in the time of money"" is...",positive


In [25]:
from sklearn.model_selection import train_test_split
train_x, test_x, train_y, test_y = train_test_split(tdm, df.Y)

from sklearn.metrics import confusion_matrix, accuracy_score,recall_score,precision_score,f1_score
from sklearn.metrics import *

train_y = train_y.map({'positive': 1, 'negative': 0})
test_y = test_y.map({'positive': 1, 'negative': 0})

train_y = train_y.astype(int)
test_y = test_y.astype(int)

In [26]:
from sklearn.linear_model import LogisticRegression
logreg = LogisticRegression()
logreg.fit(train_x, train_y)#model build

,penalty,'l2'
,dual,False
,tol,0.0001
,C,1.0
,fit_intercept,True
,intercept_scaling,1
,class_weight,None
,random_state,None
,solver,'lbfgs'
,max_iter,100
,multi_class,'deprecated'


In [27]:
pred = logreg.predict(test_x)
print(confusion_matrix(test_y,pred))
print(classification_report(test_y, pred))

[[5465  759]
 [ 669 5607]]
              precision    recall  f1-score   support

           0       0.89      0.88      0.88      6224
           1       0.88      0.89      0.89      6276

    accuracy                           0.89     12500
   macro avg       0.89      0.89      0.89     12500
weighted avg       0.89      0.89      0.89     12500



In [28]:
from sklearn.tree import DecisionTreeClassifier
dt = DecisionTreeClassifier()
dt.fit(train_x, train_y)
pred = dt.predict(test_x)
tab = confusion_matrix(test_y, pred)
print(tab)
print(
    accuracy_score(test_y, pred),
    " ",
    recall_score(test_y, pred, average='weighted'),
    " ",
    precision_score(test_y, pred, average='weighted'))

[[4560 1664]
 [1700 4576]]
0.73088   0.73088   0.7308941086261982


In [29]:
from  sklearn.ensemble import RandomForestClassifier
dt = RandomForestClassifier(oob_score=True)
dt.fit(train_x,train_y)
pred = dt.predict(test_x)
tab = confusion_matrix(test_y, pred)
print(tab)
print(accuracy_score(test_y, pred))

[[5343  881]
 [ 948 5328]]
0.85368


In [30]:
import nltk
from nltk.sentiment.vader import SentimentIntensityAnalyzer # function
nltk.download('vader_lexicon')

[nltk_data] Downloading package vader_lexicon to
[nltk_data]     /Users/anishgulhane/nltk_data...
[nltk_data]   Package vader_lexicon is already up-to-date!


True

In [31]:
sent = SentimentIntensityAnalyzer()

In [36]:
df.shape

(50000, 2)

In [38]:
df

,X,Y
0,one of the other reviewers has mentioned that ...,positive
1,a wonderful little production. <br /><br />the...,positive
2,i thought this was a wonderful way to spend ti...,positive
3,basically there's a family where a little boy ...,negative
4,"petter mattei's ""love in the time of money"" is...",positive
...,...,...
49995,i thought this movie did a down right good job...,positive
49996,"bad plot, bad dialogue, bad acting, idiotic di...",negative
49997,i am a catholic taught in parochial elementary...,negative
49998,i'm going to have to disagree with the previou...,negative


In [39]:
score_list = []

for i  in range (0, df.shape[0]):
    score= sent.polarity_scores(df['X'][i])
    score_list.append(score['compound'])

In [40]:
score_list

[-0.9947,
 0.9641,
 0.9605,
 -0.9213,
 0.9744,
 0.9828,
 0.9022,
 0.8596,
 0.2362,
 0.9149,
 0.9482,
 0.5223,
 -0.968,
 0.3425,
 0.6168,
 -0.7488,
 0.3506,
 -0.9868,
 0.6518,
 0.945,
 0.5425,
 -0.9724,
 0.7948,
 0.9343,
 -0.7602,
 0.954,
 0.9962,
 -0.7964,
 -0.9208,
 -0.987,
 -0.9907,
 -0.6468,
 -0.9604,
 0.9971,
 0.7133,
 -0.9399,
 -0.962,
 -0.9847,
 0.9838,
 0.9797,
 0.0854,
 0.9858,
 -0.4678,
 0.9818,
 0.9182,
 0.9401,
 0.9165,
 -0.68,
 -0.7114,
 0.2152,
 0.9396,
 0.9893,
 -0.9274,
 0.7416,
 -0.968,
 -0.4417,
 -0.9477,
 0.7648,
 -0.7839,
 0.992,
 0.9139,
 -0.3699,
 0.7747,
 -0.168,
 -0.6149,
 0.5004,
 -0.6416,
 0.9902,
 0.63,
 0.9422,
 0.9837,
 0.9852,
 0.6441,
 0.9813,
 0.9382,
 0.9847,
 -0.8963,
 -0.9973,
 0.4082,
 0.8498,
 0.9714,
 -0.9406,
 -0.8837,
 0.5907,
 -0.8489,
 -0.9123,
 -0.1012,
 -0.7366,
 -0.7228,
 -0.9659,
 0.9311,
 -0.0516,
 0.9943,
 0.9818,
 0.9272,
 0.9826,
 -0.9434,
 -0.9844,
 -0.984,
 0.9831,
 0.8956,
 0.9444,
 0.9437,
 -0.4877,
 -0.9497,
 0.9865,
 0.9701,
 -0.98

In [41]:
score_list = pd.DataFrame(score_list)

In [42]:
score_list.describe() 

,0
count,50000.000000
mean,0.298625
std,0.805933
min,-0.999800
25%,-0.690000
50%,0.819300
75%,0.970400
max,0.999900
